sudo: required
language: python

addons:
  sonarcloud:
    organization: "ramona484"
    token: $SONAR_TOKEN

services:
  - docker
env:
  global:
    - DOCKER_REPO=docker/repo
    - EB_REGION="us-east-1"
    - secure: $AWS_ACCOUNT_ID
    - secure: $AWS_ACCESS_KEY_ID
    - secure: $AWS_SECRET_ACCESS_KEY
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker build -t trivy-ci-test:${COMMIT} .
  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
  - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
  - docker build -t dockle-ci-test:${COMMIT} .
  - export VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
  - tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz

script:
  - sonar-scanner
  - ./trivy --exit-code 0 --severity HIGH --no-progress trivy-ci-test:${COMMIT}
  - ./trivy --exit-code 1 --severity CRITICAL --no-progress trivy-ci-test:${COMMIT}
  - ./dockle --exit-code 1 dockle-ci-test:${COMMIT}
  - docker build -t $DOCKER_REPO .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

