language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
    - docker

script:
  - docker build -t security-tests .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag security-tests $DOCKER_USER/security-tests:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/security-tests:$TRAVIS_BUILD_NUMBER
  - docker tag security-tests $DOCKER_USER/security-tests:latest
  - docker push $DOCKER_USER/security-tests:latest
