sudo: required
language: python
services:
  - docker
env:
  global:
    - DOCKER_REPO=docker/repo
    - EB_REGION="us-east-1"
    - secure: $AWS_ACCOUNT_ID
    - secure: $AWS_ACCESS_KEY_ID
    - secure: $AWS_SECRET_ACCESS_KEY
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

addons:
  sonarcloud:
    organization: ramona484 # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner