name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master 
        
      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile
          
      - name: Scan image
        uses: anchore/scan-action@v2
        with:
          image: "localbuild/testimage:latest"
          fail-build: true
          severity-cutoff: critical
          

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ramona84/security-tests:latest
